[project]
name = "webui"
version = "1.0.0"
description = ""
readme = "README.md"
authors = [
    { name = "nayetdet", email = "jpmoreiracampos21@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.51.0",
    "requests>=2.32.0",
    "pydantic>=2.12.4",
    "core",
    "python-dotenv>=1.2.1",
    "pandas>=2.3.3",
    "matplotlib>=3.10.7",
]

[project.scripts]
webui = "webui:main"

[build-system]
requires = ["uv_build>=0.9.7,<0.10.0"]
build-backend = "uv_build"

[tool.uv.sources]
core = { workspace = true }
