[project]
name = "webui"
version = "1.0.0"
description = ""
readme = "README.md"
authors = [
    { name = "nayetdet", email = "jpmoreiracampos21@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.51.0",
    "requests>=2.32.0",
    "pandas>=2.2.0",
    "altair>=5.3.0",
]

[project.scripts]
webui = "webui:main"

[build-system]
requires = ["uv_build>=0.9.7,<0.10.0"]
build-backend = "uv_build"
