[project]
name = "api"
version = "1.0.0"
description = ""
readme = "README.md"
authors = [
    { name = "nayetdet", email = "jpmoreiracampos21@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.17.1",
    "core",
    "fastapi[standard]>=0.121.0",
    "matplotlib>=3.10.7",
    "scipy>=1.16.3",
    "sqlmodel>=0.0.27",
]

[project.scripts]
api = "api:main"

[build-system]
requires = ["uv_build>=0.9.7,<0.10.0"]
build-backend = "uv_build"

[tool.uv.sources]
core = { workspace = true }

[dependency-groups]
dev = []
scripts = [
    "tabulate>=0.9.0",
]
tests = [
    "pytest>=8.4.2",
]
